baseurl: /fabacademy
exclude: ['README.md']
kramdown:
  input: GFM
  #hard_wrap: false
  #auto_ids: true
  #footnote_nr: 1
  #entity_output: as_char
  #toc_levels: 1..6
  #smart_quotes: lsquo,rsquo,ldquo,rdquo
  #enable_coderay: false

include: ['_pages']

#for every new entry in _post folder, set default layout, author,
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      author: "nikomoja"
